"""
Knowledge Agent schemas.
"""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


# ==========================================================
# Search Request
# ==========================================================

class KnowledgeSearchRequest(BaseModel):
    """
    Incoming search request.
    """

    query: str = Field(
        ...,
        min_length=2,
        max_length=2000,
    )

    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
    )


# ==========================================================
# Retrieved Document
# ==========================================================

class RetrievedDocument(BaseModel):
    """
    Represents one retrieved document chunk.
    """

    document_id: str

    content: str

    score: float

    source: str

    metadata: dict[str, Any] = Field(
        default_factory=dict,
    )


# ==========================================================
# Search Response
# ==========================================================

class KnowledgeSearchResponse(BaseModel):
    """
    Response returned by the retriever.
    """

    query: str

    documents: list[RetrievedDocument]

    model_config = ConfigDict(
        from_attributes=True,
    )


# ==========================================================
# Final AI Response
# ==========================================================

class KnowledgeResponse(BaseModel):
    """
    Final answer generated by the Knowledge Agent.
    """

    answer: str

    sources: list[str]

    generated_at: datetime

    model_config = ConfigDict(
        from_attributes=True,
    )