"""
Tool execution layer for the Knowledge Agent.

Receives function calls selected by the LLM, validates their
arguments, injects application-controlled context, and executes
the registered Knowledge Agent tool.
"""

from __future__ import annotations

import inspect
from typing import Any, get_type_hints

from pydantic import TypeAdapter, ValidationError

from core.logger import get_logger
from modules.knowledge.rag.retriever import KnowledgeRetriever
from modules.knowledge.registry import tool_registry


logger = get_logger(__name__)


class KnowledgeToolExecutionError(Exception):
    """
    Raised when a Knowledge Agent tool cannot be executed.
    """


class KnowledgeToolExecutor:
    """
    Executes Knowledge Agent tools requested by the LLM.

    Responsibilities:
    - Verify that the requested tool exists.
    - Validate LLM-generated arguments.
    - Inject tenant context and application dependencies.
    - Execute the registered async tool.
    - Return the tool result to the agent.
    """

    def __init__(
        self,
        *,
        retriever: KnowledgeRetriever,
    ) -> None:
        self._retriever = retriever

    async def execute(
        self,
        tool_name: str,
        arguments: dict[str, Any] | None = None,
        *,
        tenant_id: str,
    ) -> Any:
        """
        Execute a registered Knowledge Agent tool.

        Args:
            tool_name:
                Name of the tool requested by the LLM.

            arguments:
                JSON-compatible arguments generated by the LLM.

            tenant_id:
                Tenant identifier from the authenticated
                WorkPilot request.

        Returns:
            Result returned by the registered tool.

        Raises:
            KnowledgeToolExecutionError:
                If the tool does not exist, arguments are invalid,
                or execution fails.
        """

        arguments = arguments or {}

        logger.info(
            "Preparing Knowledge tool execution",
            tool_name=tool_name,
        )

        if not tenant_id.strip():
            raise KnowledgeToolExecutionError(
                "Tenant ID is required for Knowledge Agent tools."
            )

        if not tool_registry.exists(tool_name):
            logger.warning(
                "LLM requested unknown Knowledge tool",
                tool_name=tool_name,
            )

            raise KnowledgeToolExecutionError(
                f"Unknown Knowledge tool: {tool_name}"
            )

        handler = tool_registry.get(tool_name)

        try:
            validated_arguments = self._validate_arguments(
                handler=handler,
                arguments=arguments,
            )

            signature = inspect.signature(handler)

            # These values are controlled by WorkPilot.
            # They must never come from the LLM.
            if "tenant_id" in signature.parameters:
                validated_arguments["tenant_id"] = tenant_id

            if "retriever" in signature.parameters:
                validated_arguments["retriever"] = self._retriever

            logger.info(
                "Executing Knowledge tool",
                tool_name=tool_name,
            )

            result = handler(**validated_arguments)

            if inspect.isawaitable(result):
                result = await result

            logger.info(
                "Knowledge tool execution completed",
                tool_name=tool_name,
            )

            return result

        except KnowledgeToolExecutionError:
            raise

        except ValidationError as exc:
            logger.warning(
                "Invalid Knowledge tool arguments",
                tool_name=tool_name,
                error=str(exc),
            )

            raise KnowledgeToolExecutionError(
                f"Invalid arguments for Knowledge tool "
                f"'{tool_name}'."
            ) from exc

        except TypeError as exc:
            logger.warning(
                "Unable to call Knowledge tool",
                tool_name=tool_name,
                error=str(exc),
            )

            raise KnowledgeToolExecutionError(
                f"Invalid arguments for Knowledge tool "
                f"'{tool_name}'."
            ) from exc

        except Exception as exc:
            logger.exception(
                "Knowledge tool execution failed",
                tool_name=tool_name,
                error=str(exc),
            )

            raise KnowledgeToolExecutionError(
                f"Knowledge tool '{tool_name}' failed."
            ) from exc

    @staticmethod
    def _validate_arguments(
        *,
        handler: Any,
        arguments: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Validate LLM-generated arguments using the handler's
        Python type annotations.

        Internal application-controlled parameters are excluded
        from LLM validation and are injected by execute().
        """

        signature = inspect.signature(handler)

        try:
            type_hints = get_type_hints(handler)
        except (NameError, TypeError):
            type_hints = {}

        internal_parameters = {
            "tenant_id",
            "retriever",
            "headers",
        }

        allowed_arguments = {
            name
            for name in signature.parameters
            if name not in internal_parameters
        }

        unknown_arguments = (
            set(arguments) - allowed_arguments
        )

        if unknown_arguments:
            unknown = ", ".join(
                sorted(unknown_arguments)
            )

            raise KnowledgeToolExecutionError(
                f"Unexpected arguments for Knowledge tool: "
                f"{unknown}"
            )

        validated: dict[str, Any] = {}

        for name, parameter in signature.parameters.items():

            if name in internal_parameters:
                continue

            if name not in arguments:
                if parameter.default is inspect.Parameter.empty:
                    raise KnowledgeToolExecutionError(
                        f"Missing required argument: {name}"
                    )

                continue

            value = arguments[name]

            annotation = type_hints.get(
                name,
                parameter.annotation,
            )

            if annotation is inspect.Parameter.empty:
                validated[name] = value
                continue

            validated[name] = TypeAdapter(
                annotation
            ).validate_python(value)

        return validated


def create_knowledge_tool_executor(
    retriever: KnowledgeRetriever,
) -> KnowledgeToolExecutor:
    """
    Create a KnowledgeToolExecutor with the configured retriever.
    """

    return KnowledgeToolExecutor(
        retriever=retriever,
    )