"""
Schemas used by the HR Agent tools.

These schemas validate the arguments generated by the LLM before
they are passed to the HR Service.
"""

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field


# =====================================================
# Employee
# =====================================================

class CreateEmployeeToolInput(BaseModel):
    auth_user_id: UUID

    employee_code: str = Field(..., min_length=1, max_length=30)

    first_name: str = Field(..., min_length=1, max_length=100)

    last_name: str = Field(..., min_length=1, max_length=100)

    phone: Optional[str] = None

    joining_date: date

    employment_type: str

    employment_status: str = "ACTIVE"

    department_id: Optional[UUID] = None

    designation_id: Optional[UUID] = None

    manager_id: Optional[UUID] = None

    gender: Optional[str] = None

    date_of_birth: Optional[date] = None

    work_location: Optional[str] = None

    profile_photo: Optional[str] = None


class UpdateEmployeeToolInput(BaseModel):

    employee_id: UUID

    first_name: Optional[str] = None

    last_name: Optional[str] = None

    phone: Optional[str] = None

    employment_status: Optional[str] = None

    department_id: Optional[UUID] = None

    designation_id: Optional[UUID] = None

    manager_id: Optional[UUID] = None

    work_location: Optional[str] = None


class DeleteEmployeeToolInput(BaseModel):

    employee_id: UUID


class SearchEmployeeToolInput(BaseModel):

    keyword: str

    page: int = 1

    size: int = 10


class EmployeeProfileToolInput(BaseModel):

    employee_id: UUID


# =====================================================
# Attendance
# =====================================================

class CheckInToolInput(BaseModel):

    employee_id: UUID


class CheckOutToolInput(BaseModel):

    employee_id: UUID


class AttendanceSummaryToolInput(BaseModel):

    employee_id: UUID


class MonthlyAttendanceReportToolInput(BaseModel):

    month: int

    year: int


# =====================================================
# Leave
# =====================================================

class LeaveType(str, Enum):
    CASUAL = "CASUAL"
    SICK = "SICK"
    EARNED = "EARNED"
    MATERNITY = "MATERNITY"
    PATERNITY = "PATERNITY"
    COMP_OFF = "COMP_OFF"
    UNPAID = "UNPAID"
    OTHER = "OTHER"



class CreateLeaveRequestToolInput(BaseModel):

    employee_id: UUID

    leave_type: LeaveType

    start_date: date

    end_date: date

    reason: str

    is_half_day: bool = False


class UpdateLeaveStatusToolInput(BaseModel):

    leave_id: UUID

    status: str


class LeaveBalanceToolInput(BaseModel):

    employee_id: UUID


# =====================================================
# Organization
# =====================================================

class CreateDepartmentToolInput(BaseModel):

    name: str

    description: Optional[str] = None


class CreateDesignationToolInput(BaseModel):

    name: str

    description: Optional[str] = None

    department_id: Optional[int] = None


class CreateBranchToolInput(BaseModel):

    name: str

    code: Optional[str] = None

    address: Optional[str] = None

    city: Optional[str] = None

    state: Optional[str] = None

    country: Optional[str] = None

    postal_code: Optional[str] = None

    phone: Optional[str] = None

    email: Optional[str] = None


class CreateShiftToolInput(BaseModel):

    name: str

    start_time: str

    end_time: str

    grace_time: int = 0

    is_night_shift: bool = False


# =====================================================
# Policies
# =====================================================

class CreateLeavePolicyToolInput(BaseModel):

    name: str

    description: Optional[str] = None


class CreateAttendancePolicyToolInput(BaseModel):

    name: str

    description: Optional[str] = None


class CreateHolidayPolicyToolInput(BaseModel):

    name: str

    description: Optional[str] = None


class CreateShiftPolicyToolInput(BaseModel):

    name: str

    description: Optional[str] = None


class CreateProbationPolicyToolInput(BaseModel):

    name: str

    description: Optional[str] = None

# =====================================================
# Replaced Missing Schemas
# =====================================================

from datetime import time
from decimal import Decimal
from pydantic import BaseModel

# -- Attendance --
class CreateAttendanceToolInput(BaseModel):
    employee_id: UUID
    attendance_date: date
    check_in: time | None = None
    check_out: time | None = None
    status: str = "PRESENT"
    remarks: str | None = None

class UpdateAttendanceToolInput(BaseModel):
    attendance_date: date | None = None
    check_in: time | None = None
    check_out: time | None = None
    status: str | None = None
    remarks: str | None = None

class UpdateAttendanceStatusToolInput(BaseModel):
    status: str

# -- Leave --
class CreateLeaveTypeToolInput(BaseModel):
    name: str
    description: str | None = None
    days_per_year: int
    is_paid: bool = True
    carry_forward: bool = False

class UpdateLeaveTypeToolInput(BaseModel):
    name: str | None = None
    description: str | None = None
    days_per_year: int | None = None
    is_paid: bool | None = None
    carry_forward: bool | None = None
    is_active: bool | None = None

class CreateLeaveBalanceToolInput(BaseModel):
    employee_id: UUID
    leave_type: LeaveType
    year: int
    allocated_days: Decimal
    carried_forward_days: Decimal = Decimal("0.0")
    notes: str | None = None

class UpdateLeaveBalanceToolInput(BaseModel):
    allocated_days: Decimal | None = None
    used_days: Decimal | None = None
    carried_forward_days: Decimal | None = None
    notes: str | None = None

class CreateHolidayToolInput(BaseModel):
    name: str
    date: date
    is_optional: bool = False

class UpdateLeaveToolInput(BaseModel):
    leave_type: LeaveType | None = None
    start_date: date | None = None
    end_date: date | None = None
    reason: str | None = None
    is_half_day: bool | None = None
    emergency_contact: str | None = None

# -- Employee --
class UploadEmployeeDocumentToolInput(BaseModel):
    document_name: str
    document_type: str
    file_url: str

class UpdateEmployeeProfileToolInput(BaseModel):
    address: str | None = None
    city: str | None = None
    state: str | None = None
    country: str | None = None
    postal_code: str | None = None
    emergency_contact_name: str | None = None
    emergency_contact_phone: str | None = None
    emergency_contact_relation: str | None = None
    blood_group: str | None = None
    marital_status: str | None = None

# -- Organization --
class UpdateDepartmentToolInput(BaseModel):
    name: str | None = None
    description: str | None = None
    is_active: bool | None = None

class UpdateDesignationToolInput(BaseModel):
    name: str | None = None
    description: str | None = None
    department_id: int | None = None
    is_active: bool | None = None

class UpdateBranchToolInput(BaseModel):
    name: str | None = None
    code: str | None = None
    address: str | None = None
    city: str | None = None
    state: str | None = None
    country: str | None = None
    postal_code: str | None = None
    phone: str | None = None
    email: str | None = None
    is_active: bool | None = None

class UpdateShiftToolInput(BaseModel):
    name: str | None = None
    start_time: time | None = None
    end_time: time | None = None
    grace_time: int | None = None
    is_night_shift: bool | None = None
    is_active: bool | None = None

# -- Policies --
class UpdateLeavePolicyToolInput(BaseModel):
    name: str | None = None
    casual_leave_days: Decimal | None = None
    sick_leave_days: Decimal | None = None
    earned_leave_days: Decimal | None = None
    maternity_leave_days: Decimal | None = None
    paternity_leave_days: Decimal | None = None
    carry_forward_enabled: bool | None = None
    max_carry_forward: Decimal | None = None
    half_day_allowed: bool | None = None
    minimum_notice_days: int | None = None
    requires_attachment: bool | None = None

class UpdateAttendancePolicyToolInput(BaseModel):
    name: str | None = None
    working_hours: Decimal | None = None
    grace_period: int | None = None
    late_mark_limit: int | None = None
    half_day_after_hours: Decimal | None = None
    auto_checkout: bool | None = None
    weekend_policy: str | None = None

class UpdateShiftPolicyToolInput(BaseModel):
    name: str | None = None
    shift_start: time | None = None
    shift_end: time | None = None
    break_duration: int | None = None
    weekly_off: str | None = None
    night_shift: bool | None = None

class UpdateHolidayPolicyToolInput(BaseModel):
    name: str | None = None
    calendar_name: str | None = None
    country: str | None = None
    state: str | None = None
    floating_holidays: int | None = None

class UpdateProbationPolicyToolInput(BaseModel):
    name: str | None = None
    duration_months: int | None = None
    review_after_months: int | None = None
    confirmation_required: bool | None = None
    notice_period: int | None = None
