"""
Schemas used by the HR Agent tools.

These schemas validate the arguments generated by the LLM before
they are passed to the HR Service.
"""

from __future__ import annotations

from datetime import date
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field


# =====================================================
# Employee
# =====================================================

class CreateEmployeeToolInput(BaseModel):
    auth_user_id: UUID

    employee_code: str = Field(..., min_length=1, max_length=30)

    first_name: str = Field(..., min_length=1, max_length=100)

    last_name: str = Field(..., min_length=1, max_length=100)

    phone: Optional[str] = None

    joining_date: date

    employment_type: str

    employment_status: str = "ACTIVE"

    department_id: Optional[UUID] = None

    designation_id: Optional[UUID] = None

    manager_id: Optional[UUID] = None

    gender: Optional[str] = None

    date_of_birth: Optional[date] = None

    work_location: Optional[str] = None

    profile_photo: Optional[str] = None


class UpdateEmployeeToolInput(BaseModel):

    employee_id: UUID

    first_name: Optional[str] = None

    last_name: Optional[str] = None

    phone: Optional[str] = None

    employment_status: Optional[str] = None

    department_id: Optional[UUID] = None

    designation_id: Optional[UUID] = None

    manager_id: Optional[UUID] = None

    work_location: Optional[str] = None


class DeleteEmployeeToolInput(BaseModel):

    employee_id: UUID


class SearchEmployeeToolInput(BaseModel):

    keyword: str

    page: int = 1

    size: int = 10


class EmployeeProfileToolInput(BaseModel):

    employee_id: UUID


# =====================================================
# Attendance
# =====================================================

class CheckInToolInput(BaseModel):

    employee_id: UUID


class CheckOutToolInput(BaseModel):

    employee_id: UUID


class AttendanceSummaryToolInput(BaseModel):

    employee_id: UUID


class MonthlyAttendanceReportToolInput(BaseModel):

    month: int

    year: int


# =====================================================
# Leave
# =====================================================

class CreateLeaveRequestToolInput(BaseModel):

    employee_id: UUID

    leave_type: str

    start_date: date

    end_date: date

    reason: str

    is_half_day: bool = False


class UpdateLeaveStatusToolInput(BaseModel):

    leave_id: UUID

    status: str


class LeaveBalanceToolInput(BaseModel):

    employee_id: UUID


# =====================================================
# Organization
# =====================================================

class CreateDepartmentToolInput(BaseModel):

    name: str

    description: Optional[str] = None


class CreateDesignationToolInput(BaseModel):

    name: str

    description: Optional[str] = None

    department_id: Optional[int] = None


class CreateBranchToolInput(BaseModel):

    name: str

    code: Optional[str] = None

    address: Optional[str] = None

    city: Optional[str] = None

    state: Optional[str] = None

    country: Optional[str] = None

    postal_code: Optional[str] = None

    phone: Optional[str] = None

    email: Optional[str] = None


class CreateShiftToolInput(BaseModel):

    name: str

    start_time: str

    end_time: str

    grace_time: int = 0

    is_night_shift: bool = False


# =====================================================
# Policies
# =====================================================

class CreateLeavePolicyToolInput(BaseModel):

    name: str

    description: Optional[str] = None


class CreateAttendancePolicyToolInput(BaseModel):

    name: str

    description: Optional[str] = None


class CreateHolidayPolicyToolInput(BaseModel):

    name: str

    description: Optional[str] = None


class CreateShiftPolicyToolInput(BaseModel):

    name: str

    description: Optional[str] = None


class CreateProbationPolicyToolInput(BaseModel):

    name: str

    description: Optional[str] = None

# =====================================================
# Auto-generated Missing Schemas
# =====================================================

class AttendanceCheckInToolInput(BaseModel):
    # TODO: Add specific fields
    name: str = ""

class AttendanceCheckOutToolInput(BaseModel):
    # TODO: Add specific fields
    name: str = ""

class CreateAttendanceToolInput(BaseModel):
    # TODO: Add specific fields
    name: str = ""

class CreateHolidayToolInput(BaseModel):
    # TODO: Add specific fields
    name: str = ""

class CreateLeaveBalanceToolInput(BaseModel):
    # TODO: Add specific fields
    name: str = ""

class CreateLeaveToolInput(BaseModel):
    # TODO: Add specific fields
    name: str = ""

class CreateLeaveTypeToolInput(BaseModel):
    # TODO: Add specific fields
    name: str = ""

class UpdateAttendancePolicyToolInput(BaseModel):
    # TODO: Add specific fields
    payload: dict

class UpdateAttendanceStatusToolInput(BaseModel):
    # TODO: Add specific fields
    status: str

class UpdateAttendanceToolInput(BaseModel):
    # TODO: Add specific fields
    payload: dict

class UpdateBranchToolInput(BaseModel):
    # TODO: Add specific fields
    payload: dict

class UpdateDepartmentToolInput(BaseModel):
    # TODO: Add specific fields
    payload: dict

class UpdateDesignationToolInput(BaseModel):
    # TODO: Add specific fields
    payload: dict

class UpdateEmployeeProfileToolInput(BaseModel):
    # TODO: Add specific fields
    payload: dict

class UpdateHolidayPolicyToolInput(BaseModel):
    # TODO: Add specific fields
    payload: dict

class UpdateLeaveBalanceToolInput(BaseModel):
    # TODO: Add specific fields
    payload: dict

class UpdateLeavePolicyToolInput(BaseModel):
    # TODO: Add specific fields
    payload: dict

class UpdateLeaveToolInput(BaseModel):
    # TODO: Add specific fields
    payload: dict

class UpdateLeaveToolInputStatus(BaseModel):
    # TODO: Add specific fields
    status: str

class UpdateLeaveTypeToolInput(BaseModel):
    # TODO: Add specific fields
    payload: dict

class UpdateProbationPolicyToolInput(BaseModel):
    # TODO: Add specific fields
    payload: dict

class UpdateShiftPolicyToolInput(BaseModel):
    # TODO: Add specific fields
    payload: dict

class UpdateShiftToolInput(BaseModel):
    # TODO: Add specific fields
    payload: dict

class UploadEmployeeDocumentToolInput(BaseModel):
    # TODO: Add specific fields
    name: str = ""