"""
Orchestration Planner for the Coordinator Agent.

This module is responsible for breaking down a high-level user intent into a 
structured sequence of execution steps. It strictly dictates "what" needs to be 
done, but never "how" to do it (leaving business execution to specialist agents).
"""

from typing import List
from pydantic import BaseModel, Field

from core.logger import get_logger
from modules.coordinator.client import coordinator_llm_client
from modules.coordinator.exceptions import PlannerError
from modules.coordinator.prompts import build_planner_prompt
from modules.coordinator.intent_detector import IntentClassification


logger = get_logger(__name__)


class PlanStep(BaseModel):
    """
    Represents a single abstract step in an execution plan.
    """
    step_number: int = Field(..., description="The sequential order of this step.")
    description: str = Field(..., description="A high-level instruction for the specialist agent.")


class ExecutionPlan(BaseModel):
    """
    The complete, sequential execution plan generated by the LLM.
    """
    plan: List[PlanStep] = Field(default_factory=list, description="Ordered list of steps to execute.")


class OrchestrationPlanner:
    """
    Generates multi-step execution plans based on the user's intent.
    """

    async def generate_plan(
        self, 
        user_message: str, 
        intent_classification: IntentClassification
    ) -> ExecutionPlan:
        """
        Calls the LLM to generate a sequence of abstract steps required to fulfill the request.
        
        Args:
            user_message (str): The original natural language request.
            intent_classification (IntentClassification): The detected domain and intent.
            
        Returns:
            ExecutionPlan: A strongly-typed, ordered list of execution steps.
            
        Raises:
            PlannerError: If the LLM fails to generate a valid, structured plan.
        """
        logger.info(
            "Generating execution plan", 
            domain=intent_classification.domain,
            intent=intent_classification.intent
        )
        
        prompt = build_planner_prompt(
            domain=intent_classification.domain,
            intent=intent_classification.intent,
            user_message=user_message,
        )
        
        try:
            # Enforce strict JSON generation via the coordinator client
            raw_result = await coordinator_llm_client.generate_structured_json(prompt)
            execution_plan = ExecutionPlan(**raw_result)
            
        except Exception as e:
            logger.error("Failed to parse execution plan from LLM", error=str(e))
            raise PlannerError(f"Planner failed to generate valid JSON plan: {str(e)}") from e
            
        # Validate that the LLM actually produced steps
        if not execution_plan.plan:
            logger.error("Planner generated an empty execution plan.")
            raise PlannerError("Planner generated an empty execution plan.")
            
        # Ensure the steps are reliably sorted by their intended step_number
        execution_plan.plan.sort(key=lambda step: step.step_number)
        
        logger.info(
            "Execution plan generated successfully",
            total_steps=len(execution_plan.plan)
        )
        
        return execution_plan


# Singleton instance for the coordinator module
orchestration_planner = OrchestrationPlanner()
