"""Add dlq_events table

Revision ID: 4679833ff5a3
Revises: f82b305bd0a2
Create Date: 2026-08-18 20:08:44.420455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4679833ff5a3'
down_revision: Union[str, Sequence[str], None] = 'f82b305bd0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dlq_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dlq_events_event_id'), 'dlq_events', ['event_id'], unique=False)
    op.drop_index(op.f('ix_ticket_comments_author_id'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_ticket_id'), table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_table('attendance_policies')
    op.drop_index(op.f('ix_ticket_assigned_to'), table_name='tickets')
    op.drop_index(op.f('ix_ticket_priority'), table_name='tickets')
    op.drop_index(op.f('ix_ticket_requester'), table_name='tickets')
    op.drop_index(op.f('ix_ticket_status'), table_name='tickets')
    op.drop_index(op.f('ix_ticket_ticket_number'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('holiday_policies')
    op.drop_index(op.f('ix_installed_software_device_id'), table_name='installed_software')
    op.drop_index(op.f('ix_installed_software_software_id'), table_name='installed_software')
    op.drop_index(op.f('ix_installed_software_user_id'), table_name='installed_software')
    op.drop_table('installed_software')
    op.drop_index(op.f('ix_assets_assigned_to'), table_name='assets')
    op.drop_index(op.f('ix_assets_serial_number'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_schema_name'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_devices_assigned_to'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_ticket_attachments_ticket_id'), table_name='ticket_attachments')
    op.drop_index(op.f('ix_ticket_attachments_uploaded_by'), table_name='ticket_attachments')
    op.drop_table('ticket_attachments')
    op.drop_index(op.f('ix_maintenance_records_device_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_status'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_leave_balances_employee_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index(op.f('ix_ticket_activity_performed_by'), table_name='ticket_activity_logs')
    op.drop_index(op.f('ix_ticket_activity_ticket_id'), table_name='ticket_activity_logs')
    op.drop_table('ticket_activity_logs')
    op.drop_table('software')
    op.drop_index(op.f('uq_employees_auth_user_id_active'), table_name='employees', postgresql_where='(is_active = true)')
    op.drop_index(op.f('uq_employees_employee_code_active'), table_name='employees', postgresql_where='(is_active = true)')
    op.drop_table('employees')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_workflow_instance_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_install_req_software_id'), table_name='software_installation_requests')
    op.drop_index(op.f('ix_install_req_user_id'), table_name='software_installation_requests')
    op.drop_table('software_installation_requests')
    op.drop_index(op.f('ix_domains_domain'), table_name='domains')
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_device_maintenance_device_id'), table_name='device_maintenance_history')
    op.drop_table('device_maintenance_history')
    op.drop_table('password_reset_tokens')
    op.drop_table('employee_profiles')
    op.drop_table('leave_policies')
    op.drop_index(op.f('ix_invitations_expires_at'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_tenant_email'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_token_hash'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_attendance_attendance_date'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_leave_types_id'), table_name='leave_types')
    op.drop_table('leave_types')
    op.drop_table('alembic_version_workflow')
    op.drop_table('employee_documents')
    op.drop_table('alembic_version_hr')
    op.drop_table('approvals')
    op.drop_table('probation_policies')
    op.drop_table('shift_policies')
    op.drop_index(op.f('ix_access_requests_requested_by'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_status'), table_name='access_requests')
    op.drop_table('access_requests')
    op.drop_index(op.f('ix_revoked_tokens_token'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_license_assignments_assigned_to'), table_name='license_assignments')
    op.drop_index(op.f('ix_license_assignments_license_id'), table_name='license_assignments')
    op.drop_table('license_assignments')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_table('workflow_executions')
    op.drop_table('alembic_version')
    op.drop_table('workflows')
    op.drop_table('alembic_version_it')
    op.drop_table('alembic_version_notification')
    op.create_foreign_key(None, 'fact_workflow_step', 'dim_tenant', ['tenant_key'], ['id'])
    op.create_foreign_key(None, 'fact_workflow_step', 'dim_employee', ['approver_key'], ['id'])
    op.create_foreign_key(None, 'fact_workflow_step', 'dim_date', ['date_key'], ['id'])
    op.create_foreign_key(None, 'fact_workflow_step', 'dim_workflow', ['workflow_key'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_workflow_step', type_='foreignkey')
    op.drop_constraint(None, 'fact_workflow_step', type_='foreignkey')
    op.drop_constraint(None, 'fact_workflow_step', type_='foreignkey')
    op.drop_constraint(None, 'fact_workflow_step', type_='foreignkey')
    op.create_table('alembic_version_notification',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_notification_pkc'))
    )
    op.create_table('alembic_version_it',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_it_pkc'))
    )
    op.create_table('workflows',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('workflows_pkey'))
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('workflow_executions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('current_step', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('started_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('workflow_executions_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_executions_pkey'))
    )
    op.create_table('holidays',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_optional', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('holidays_pkey'))
    )
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('approver_role', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('workflow_steps_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_steps_pkey'))
    )
    op.create_table('license_assignments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('license_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], name=op.f('license_assignments_license_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('license_assignments_pkey'))
    )
    op.create_index(op.f('ix_license_assignments_license_id'), 'license_assignments', ['license_id'], unique=False)
    op.create_index(op.f('ix_license_assignments_assigned_to'), 'license_assignments', ['assigned_to'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('revoked_tokens_pkey'))
    )
    op.create_index(op.f('ix_revoked_tokens_token'), 'revoked_tokens', ['token'], unique=True)
    op.create_table('access_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_type', postgresql.ENUM('VPN', 'APPLICATION', 'DATABASE', name='accessrequesttype'), autoincrement=False, nullable=False),
    sa.Column('target_resource', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'REVOKED', name='accessrequeststatus'), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('access_requests_pkey'))
    )
    op.create_index(op.f('ix_access_requests_status'), 'access_requests', ['status'], unique=False)
    op.create_index(op.f('ix_access_requests_requested_by'), 'access_requests', ['requested_by'], unique=False)
    op.create_table('shift_policies',
    sa.Column('shift_start', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('shift_end', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('break_duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weekly_off', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('night_shift', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('shift_policies_pkey'))
    )
    op.create_table('probation_policies',
    sa.Column('duration_months', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review_after_months', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confirmation_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notice_period', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('probation_policies_pkey'))
    )
    op.create_table('approvals',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('execution_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('approver_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('decision', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], name=op.f('approvals_execution_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('approvals_pkey'))
    )
    op.create_table('alembic_version_hr',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_hr_pkc'))
    )
    op.create_table('employee_documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_documents_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_documents_pkey'))
    )
    op.create_table('alembic_version_workflow',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_workflow_pkc'))
    )
    op.create_table('leave_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('days_per_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('carry_forward', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('leave_types_pkey')),
    sa.UniqueConstraint('name', name=op.f('leave_types_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_leave_types_id'), 'leave_types', ['id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attendance_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_in', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('check_out', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PRESENT', 'ABSENT', 'HALF_DAY', 'LATE', name='attendance_status'), autoincrement=False, nullable=False),
    sa.Column('working_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('overtime_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('attendance_employee_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_pkey')),
    sa.UniqueConstraint('employee_id', 'attendance_date', name=op.f('uq_employee_attendance_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_attendance_date'), 'attendance', ['attendance_date'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ORG_ADMIN', 'HR_ADMIN', 'IT_ADMIN', 'MANAGER', 'EMPLOYEE', name='role'), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitationstatus'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('accepted_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], name=op.f('invitations_accepted_by_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('invitations_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('invitations_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('invitations_pkey'))
    )
    op.create_index(op.f('ix_invitations_token_hash'), 'invitations', ['token_hash'], unique=True)
    op.create_index(op.f('ix_invitations_tenant_email'), 'invitations', ['tenant_id', 'email'], unique=False)
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitations_expires_at'), 'invitations', ['expires_at'], unique=False)
    op.create_table('leave_policies',
    sa.Column('casual_leave_days', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=False),
    sa.Column('sick_leave_days', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=False),
    sa.Column('earned_leave_days', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=False),
    sa.Column('maternity_leave_days', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=False),
    sa.Column('paternity_leave_days', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=False),
    sa.Column('carry_forward_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('max_carry_forward', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=False),
    sa.Column('half_day_allowed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('minimum_notice_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requires_attachment', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('leave_policies_pkey'))
    )
    op.create_table('employee_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('emergency_contact_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('emergency_contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('emergency_contact_relation', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('blood_group', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('marital_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_profiles_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_profiles_pkey')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_employee_profiles_employee_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey'))
    )
    op.create_table('device_maintenance_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('maintenance_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('device_maintenance_history_device_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('device_maintenance_history_pkey'))
    )
    op.create_index(op.f('ix_device_maintenance_device_id'), 'device_maintenance_history', ['device_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_mfa_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('mfa_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('mfa_enabled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('mfa_last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('domains',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('domains_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('domains_pkey'))
    )
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)
    op.create_index(op.f('ix_domains_domain'), 'domains', ['domain'], unique=True)
    op.create_table('software_installation_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('software_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='installationrequeststatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], name=op.f('software_installation_requests_software_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('software_installation_requests_pkey'))
    )
    op.create_index(op.f('ix_install_req_user_id'), 'software_installation_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_install_req_software_id'), 'software_installation_requests', ['software_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('leave_type', postgresql.ENUM('CASUAL', 'SICK', 'EARNED', 'MATERNITY', 'PATERNITY', 'COMP_OFF', 'UNPAID', 'OTHER', name='leave_type_enum'), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_half_day', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('attachment_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('emergency_contact', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leave_status_enum'), autoincrement=False, nullable=False),
    sa.Column('workflow_instance_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('leave_requests_employee_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('leave_requests_pkey'))
    )
    op.create_index(op.f('ix_leave_requests_workflow_instance_id'), 'leave_requests', ['workflow_instance_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('auth_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('employee_code', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('employment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('employment_status', sa.VARCHAR(length=50), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('designation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('manager_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('work_location', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('profile_photo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('invitation_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], name=op.f('fk_employees_manager_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('employees_pkey'))
    )
    op.create_index(op.f('uq_employees_employee_code_active'), 'employees', ['employee_code'], unique=True, postgresql_where='(is_active = true)')
    op.create_index(op.f('uq_employees_auth_user_id_active'), 'employees', ['auth_user_id'], unique=True, postgresql_where='(is_active = true)')
    op.create_table('software',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('publisher', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('license_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('software_pkey'))
    )
    op.create_table('ticket_activity_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('old_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('ticket_activity_logs_ticket_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ticket_activity_logs_pkey'))
    )
    op.create_index(op.f('ix_ticket_activity_ticket_id'), 'ticket_activity_logs', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_activity_performed_by'), 'ticket_activity_logs', ['performed_by'], unique=False)
    op.create_table('leave_balances',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('leave_type', postgresql.ENUM('CASUAL', 'SICK', 'EARNED', 'MATERNITY', 'PATERNITY', 'COMP_OFF', 'UNPAID', 'OTHER', name='leave_type_enum'), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('allocated_days', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=False),
    sa.Column('used_days', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=False),
    sa.Column('carried_forward_days', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('leave_balances_employee_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('leave_balances_pkey'))
    )
    op.create_index(op.f('ix_leave_balances_employee_id'), 'leave_balances', ['employee_id'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('maintenance_type', postgresql.ENUM('PREVENTIVE', 'CORRECTIVE', name='maintenancetype'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vendor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vendor_contact', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='maintenancestatus'), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('maintenance_records_pkey'))
    )
    op.create_index(op.f('ix_maintenance_records_status'), 'maintenance_records', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_records_device_id'), 'maintenance_records', ['device_id'], unique=False)
    op.create_table('ticket_attachments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('ticket_attachments_ticket_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ticket_attachments_pkey'))
    )
    op.create_index(op.f('ix_ticket_attachments_uploaded_by'), 'ticket_attachments', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_ticket_attachments_ticket_id'), 'ticket_attachments', ['ticket_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('user_profiles_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'REPAIR', 'RETIRED', name='devicestatus'), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('devices_pkey'))
    )
    op.create_index(op.f('ix_devices_assigned_to'), 'devices', ['assigned_to'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='tenantstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tenants_pkey')),
    sa.UniqueConstraint('company_name', name=op.f('tenants_company_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tenants_schema_name'), 'tenants', ['schema_name'], unique=True)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('software_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('license_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('total_seats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('used_seats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('renewal_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], name=op.f('licenses_software_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('licenses_pkey'))
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('LAPTOP', 'DESKTOP', 'MONITOR', 'PHONE', 'OTHER', name='assetcategory'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('AVAILABLE', 'ASSIGNED', 'UNDER_MAINTENANCE', 'DISPOSED', name='assetstatus'), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('assets_pkey')),
    sa.UniqueConstraint('serial_number', name=op.f('assets_serial_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_assets_serial_number'), 'assets', ['serial_number'], unique=False)
    op.create_index(op.f('ix_assets_assigned_to'), 'assets', ['assigned_to'], unique=False)
    op.create_table('installed_software',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('software_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('installed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], name=op.f('installed_software_software_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('installed_software_pkey'))
    )
    op.create_index(op.f('ix_installed_software_user_id'), 'installed_software', ['user_id'], unique=False)
    op.create_index(op.f('ix_installed_software_software_id'), 'installed_software', ['software_id'], unique=False)
    op.create_index(op.f('ix_installed_software_device_id'), 'installed_software', ['device_id'], unique=False)
    op.create_table('holiday_policies',
    sa.Column('calendar_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('floating_holidays', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('holiday_policies_pkey'))
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticket_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('HARDWARE', 'SOFTWARE', 'NETWORK', 'VPN', 'ACCESS_CONTROL', 'EMAIL', 'SECURITY', 'LICENSE', 'PRINTER', 'OTHER', name='ticketcategory'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'CANCELLED', name='ticketstatus'), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('WEB', 'MOBILE', 'EMAIL', 'AI_AGENT', 'ADMIN', name='ticketsource'), autoincrement=False, nullable=False),
    sa.Column('requester_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('resolution', postgresql.ENUM('FIXED', 'WORKAROUND', 'DUPLICATE', 'CANNOT_REPRODUCE', 'NOT_AN_ISSUE', name='ticketresolution'), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tickets_pkey')),
    sa.UniqueConstraint('ticket_number', name=op.f('tickets_ticket_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_ticket_ticket_number'), 'tickets', ['ticket_number'], unique=False)
    op.create_index(op.f('ix_ticket_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_ticket_requester'), 'tickets', ['requester_id'], unique=False)
    op.create_index(op.f('ix_ticket_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_ticket_assigned_to'), 'tickets', ['assigned_to'], unique=False)
    op.create_table('attendance_policies',
    sa.Column('working_hours', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('grace_period', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('late_mark_limit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('half_day_after_hours', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('auto_checkout', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('weekend_policy', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_policies_pkey'))
    )
    op.create_table('ticket_comments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('comment_type', postgresql.ENUM('PUBLIC', 'INTERNAL', name='commenttype'), autoincrement=False, nullable=False),
    sa.Column('is_edited', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('ticket_comments_ticket_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ticket_comments_pkey'))
    )
    op.create_index(op.f('ix_ticket_comments_ticket_id'), 'ticket_comments', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_comments_author_id'), 'ticket_comments', ['author_id'], unique=False)
    op.drop_index(op.f('ix_dlq_events_event_id'), table_name='dlq_events')
    op.drop_table('dlq_events')
    # ### end Alembic commands ###
