"""Initial Star Schema

Revision ID: d0398e5af1af
Revises: 
Create Date: 2026-08-17 20:53:02.063381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0398e5af1af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_asset',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_asset_asset_id'), 'dim_asset', ['asset_id'], unique=False)
    op.create_index(op.f('ix_dim_asset_tenant_id'), 'dim_asset', ['tenant_id'], unique=False)
    op.create_table('dim_branch',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_branch_branch_id'), 'dim_branch', ['branch_id'], unique=False)
    op.create_index(op.f('ix_dim_branch_tenant_id'), 'dim_branch', ['tenant_id'], unique=False)
    op.create_table('dim_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('dim_department',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_department_department_id'), 'dim_department', ['department_id'], unique=False)
    op.create_index(op.f('ix_dim_department_tenant_id'), 'dim_department', ['tenant_id'], unique=False)
    op.create_table('dim_designation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('designation_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_designation_designation_id'), 'dim_designation', ['designation_id'], unique=False)
    op.create_index(op.f('ix_dim_designation_tenant_id'), 'dim_designation', ['tenant_id'], unique=False)
    op.create_table('dim_device',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_device_device_id'), 'dim_device', ['device_id'], unique=False)
    op.create_index(op.f('ix_dim_device_tenant_id'), 'dim_device', ['tenant_id'], unique=False)
    op.create_table('dim_employee',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_employee_employee_id'), 'dim_employee', ['employee_id'], unique=False)
    op.create_index(op.f('ix_dim_employee_tenant_id'), 'dim_employee', ['tenant_id'], unique=False)
    op.create_table('dim_license',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('license_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('license_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_license_license_id'), 'dim_license', ['license_id'], unique=False)
    op.create_index(op.f('ix_dim_license_tenant_id'), 'dim_license', ['tenant_id'], unique=False)
    op.create_table('dim_software',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('software_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('publisher', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_software_software_id'), 'dim_software', ['software_id'], unique=False)
    op.create_index(op.f('ix_dim_software_tenant_id'), 'dim_software', ['tenant_id'], unique=False)
    op.create_table('dim_tenant',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_tenant_tenant_id'), 'dim_tenant', ['tenant_id'], unique=True)
    op.create_table('dim_workflow',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workflow_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_workflow_tenant_id'), 'dim_workflow', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_dim_workflow_workflow_id'), 'dim_workflow', ['workflow_id'], unique=False)
    op.create_table('fact_ai_interaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_key', sa.BigInteger(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('employee_key', sa.BigInteger(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('intent', sa.String(length=150), nullable=False),
    sa.Column('tool', sa.String(length=150), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['date_key'], ['dim_date.id'], ),
    sa.ForeignKeyConstraint(['employee_key'], ['dim_employee.id'], ),
    sa.ForeignKeyConstraint(['tenant_key'], ['dim_tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_ai_interaction_date_key'), 'fact_ai_interaction', ['date_key'], unique=False)
    op.create_index(op.f('ix_fact_ai_interaction_employee_key'), 'fact_ai_interaction', ['employee_key'], unique=False)
    op.create_index(op.f('ix_fact_ai_interaction_source_event_id'), 'fact_ai_interaction', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_fact_ai_interaction_tenant_key'), 'fact_ai_interaction', ['tenant_key'], unique=False)
    op.create_table('fact_attendance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_key', sa.BigInteger(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('employee_key', sa.BigInteger(), nullable=False),
    sa.Column('department_key', sa.BigInteger(), nullable=True),
    sa.Column('designation_key', sa.BigInteger(), nullable=True),
    sa.Column('branch_key', sa.BigInteger(), nullable=True),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('worked_minutes', sa.Integer(), nullable=True),
    sa.Column('late_minutes', sa.Integer(), nullable=True),
    sa.Column('overtime_minutes', sa.Integer(), nullable=True),
    sa.Column('attendance_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['branch_key'], ['dim_branch.id'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dim_date.id'], ),
    sa.ForeignKeyConstraint(['department_key'], ['dim_department.id'], ),
    sa.ForeignKeyConstraint(['designation_key'], ['dim_designation.id'], ),
    sa.ForeignKeyConstraint(['employee_key'], ['dim_employee.id'], ),
    sa.ForeignKeyConstraint(['tenant_key'], ['dim_tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_attendance_date_key'), 'fact_attendance', ['date_key'], unique=False)
    op.create_index(op.f('ix_fact_attendance_employee_key'), 'fact_attendance', ['employee_key'], unique=False)
    op.create_index(op.f('ix_fact_attendance_source_event_id'), 'fact_attendance', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_fact_attendance_tenant_key'), 'fact_attendance', ['tenant_key'], unique=False)
    op.create_table('fact_it_ticket',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_key', sa.BigInteger(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('employee_key', sa.BigInteger(), nullable=False),
    sa.Column('department_key', sa.BigInteger(), nullable=True),
    sa.Column('asset_key', sa.BigInteger(), nullable=True),
    sa.Column('device_key', sa.BigInteger(), nullable=True),
    sa.Column('software_key', sa.BigInteger(), nullable=True),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolution_time_minutes', sa.Integer(), nullable=True),
    sa.Column('first_response_minutes', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sla_breached', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_key'], ['dim_asset.id'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dim_date.id'], ),
    sa.ForeignKeyConstraint(['department_key'], ['dim_department.id'], ),
    sa.ForeignKeyConstraint(['device_key'], ['dim_device.id'], ),
    sa.ForeignKeyConstraint(['employee_key'], ['dim_employee.id'], ),
    sa.ForeignKeyConstraint(['software_key'], ['dim_software.id'], ),
    sa.ForeignKeyConstraint(['tenant_key'], ['dim_tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_it_ticket_date_key'), 'fact_it_ticket', ['date_key'], unique=False)
    op.create_index(op.f('ix_fact_it_ticket_employee_key'), 'fact_it_ticket', ['employee_key'], unique=False)
    op.create_index(op.f('ix_fact_it_ticket_source_event_id'), 'fact_it_ticket', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_fact_it_ticket_tenant_key'), 'fact_it_ticket', ['tenant_key'], unique=False)
    op.create_table('fact_leave',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_key', sa.BigInteger(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('employee_key', sa.BigInteger(), nullable=False),
    sa.Column('department_key', sa.BigInteger(), nullable=True),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('leave_days_requested', sa.Integer(), nullable=False),
    sa.Column('decision_time_minutes', sa.Integer(), nullable=True),
    sa.Column('leave_status', sa.String(length=50), nullable=False),
    sa.Column('leave_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['date_key'], ['dim_date.id'], ),
    sa.ForeignKeyConstraint(['department_key'], ['dim_department.id'], ),
    sa.ForeignKeyConstraint(['employee_key'], ['dim_employee.id'], ),
    sa.ForeignKeyConstraint(['tenant_key'], ['dim_tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_leave_date_key'), 'fact_leave', ['date_key'], unique=False)
    op.create_index(op.f('ix_fact_leave_employee_key'), 'fact_leave', ['employee_key'], unique=False)
    op.create_index(op.f('ix_fact_leave_source_event_id'), 'fact_leave', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_fact_leave_tenant_key'), 'fact_leave', ['tenant_key'], unique=False)
    op.create_table('fact_notification',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_key', sa.BigInteger(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('employee_key', sa.BigInteger(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivery_time_ms', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['date_key'], ['dim_date.id'], ),
    sa.ForeignKeyConstraint(['employee_key'], ['dim_employee.id'], ),
    sa.ForeignKeyConstraint(['tenant_key'], ['dim_tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_notification_date_key'), 'fact_notification', ['date_key'], unique=False)
    op.create_index(op.f('ix_fact_notification_employee_key'), 'fact_notification', ['employee_key'], unique=False)
    op.create_index(op.f('ix_fact_notification_source_event_id'), 'fact_notification', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_fact_notification_tenant_key'), 'fact_notification', ['tenant_key'], unique=False)
    op.create_table('fact_workflow_execution',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_key', sa.BigInteger(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('employee_key', sa.BigInteger(), nullable=False),
    sa.Column('workflow_key', sa.BigInteger(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('total_completion_minutes', sa.Integer(), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=True),
    sa.Column('execution_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['date_key'], ['dim_date.id'], ),
    sa.ForeignKeyConstraint(['employee_key'], ['dim_employee.id'], ),
    sa.ForeignKeyConstraint(['tenant_key'], ['dim_tenant.id'], ),
    sa.ForeignKeyConstraint(['workflow_key'], ['dim_workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_workflow_execution_date_key'), 'fact_workflow_execution', ['date_key'], unique=False)
    op.create_index(op.f('ix_fact_workflow_execution_employee_key'), 'fact_workflow_execution', ['employee_key'], unique=False)
    op.create_index(op.f('ix_fact_workflow_execution_source_event_id'), 'fact_workflow_execution', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_fact_workflow_execution_tenant_key'), 'fact_workflow_execution', ['tenant_key'], unique=False)
    op.create_index(op.f('ix_fact_workflow_execution_workflow_key'), 'fact_workflow_execution', ['workflow_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_workflow_execution_workflow_key'), table_name='fact_workflow_execution')
    op.drop_index(op.f('ix_fact_workflow_execution_tenant_key'), table_name='fact_workflow_execution')
    op.drop_index(op.f('ix_fact_workflow_execution_source_event_id'), table_name='fact_workflow_execution')
    op.drop_index(op.f('ix_fact_workflow_execution_employee_key'), table_name='fact_workflow_execution')
    op.drop_index(op.f('ix_fact_workflow_execution_date_key'), table_name='fact_workflow_execution')
    op.drop_table('fact_workflow_execution')
    op.drop_index(op.f('ix_fact_notification_tenant_key'), table_name='fact_notification')
    op.drop_index(op.f('ix_fact_notification_source_event_id'), table_name='fact_notification')
    op.drop_index(op.f('ix_fact_notification_employee_key'), table_name='fact_notification')
    op.drop_index(op.f('ix_fact_notification_date_key'), table_name='fact_notification')
    op.drop_table('fact_notification')
    op.drop_index(op.f('ix_fact_leave_tenant_key'), table_name='fact_leave')
    op.drop_index(op.f('ix_fact_leave_source_event_id'), table_name='fact_leave')
    op.drop_index(op.f('ix_fact_leave_employee_key'), table_name='fact_leave')
    op.drop_index(op.f('ix_fact_leave_date_key'), table_name='fact_leave')
    op.drop_table('fact_leave')
    op.drop_index(op.f('ix_fact_it_ticket_tenant_key'), table_name='fact_it_ticket')
    op.drop_index(op.f('ix_fact_it_ticket_source_event_id'), table_name='fact_it_ticket')
    op.drop_index(op.f('ix_fact_it_ticket_employee_key'), table_name='fact_it_ticket')
    op.drop_index(op.f('ix_fact_it_ticket_date_key'), table_name='fact_it_ticket')
    op.drop_table('fact_it_ticket')
    op.drop_index(op.f('ix_fact_attendance_tenant_key'), table_name='fact_attendance')
    op.drop_index(op.f('ix_fact_attendance_source_event_id'), table_name='fact_attendance')
    op.drop_index(op.f('ix_fact_attendance_employee_key'), table_name='fact_attendance')
    op.drop_index(op.f('ix_fact_attendance_date_key'), table_name='fact_attendance')
    op.drop_table('fact_attendance')
    op.drop_index(op.f('ix_fact_ai_interaction_tenant_key'), table_name='fact_ai_interaction')
    op.drop_index(op.f('ix_fact_ai_interaction_source_event_id'), table_name='fact_ai_interaction')
    op.drop_index(op.f('ix_fact_ai_interaction_employee_key'), table_name='fact_ai_interaction')
    op.drop_index(op.f('ix_fact_ai_interaction_date_key'), table_name='fact_ai_interaction')
    op.drop_table('fact_ai_interaction')
    op.drop_index(op.f('ix_dim_workflow_workflow_id'), table_name='dim_workflow')
    op.drop_index(op.f('ix_dim_workflow_tenant_id'), table_name='dim_workflow')
    op.drop_table('dim_workflow')
    op.drop_index(op.f('ix_dim_tenant_tenant_id'), table_name='dim_tenant')
    op.drop_table('dim_tenant')
    op.drop_index(op.f('ix_dim_software_tenant_id'), table_name='dim_software')
    op.drop_index(op.f('ix_dim_software_software_id'), table_name='dim_software')
    op.drop_table('dim_software')
    op.drop_index(op.f('ix_dim_license_tenant_id'), table_name='dim_license')
    op.drop_index(op.f('ix_dim_license_license_id'), table_name='dim_license')
    op.drop_table('dim_license')
    op.drop_index(op.f('ix_dim_employee_tenant_id'), table_name='dim_employee')
    op.drop_index(op.f('ix_dim_employee_employee_id'), table_name='dim_employee')
    op.drop_table('dim_employee')
    op.drop_index(op.f('ix_dim_device_tenant_id'), table_name='dim_device')
    op.drop_index(op.f('ix_dim_device_device_id'), table_name='dim_device')
    op.drop_table('dim_device')
    op.drop_index(op.f('ix_dim_designation_tenant_id'), table_name='dim_designation')
    op.drop_index(op.f('ix_dim_designation_designation_id'), table_name='dim_designation')
    op.drop_table('dim_designation')
    op.drop_index(op.f('ix_dim_department_tenant_id'), table_name='dim_department')
    op.drop_index(op.f('ix_dim_department_department_id'), table_name='dim_department')
    op.drop_table('dim_department')
    op.drop_table('dim_date')
    op.drop_index(op.f('ix_dim_branch_tenant_id'), table_name='dim_branch')
    op.drop_index(op.f('ix_dim_branch_branch_id'), table_name='dim_branch')
    op.drop_table('dim_branch')
    op.drop_index(op.f('ix_dim_asset_tenant_id'), table_name='dim_asset')
    op.drop_index(op.f('ix_dim_asset_asset_id'), table_name='dim_asset')
    op.drop_table('dim_asset')
    # ### end Alembic commands ###
