"""
Tool execution layer for the IT Agent.

Receives function calls selected by the LLM, validates their arguments
against the registered Python tool signature, and executes the tool
through the IT Tool Registry.
"""

from __future__ import annotations

import inspect
from typing import Any, get_type_hints

from pydantic import BaseModel, TypeAdapter, ValidationError

from core.logger import get_logger
from modules.it.registry import tool_registry

logger = get_logger(__name__)


class ITToolExecutionError(Exception):
    """Raised when an IT tool cannot be executed successfully."""


class ITToolExecutor:
    """
    Executes IT tools requested by the LLM.

    Responsibilities:
    - Verify that the requested tool exists.
    - Validate and convert LLM-generated arguments.
    - Execute the registered async tool.
    - Return the result to the agent.
    """

    async def execute(
        self,
        tool_name: str,
        arguments: dict[str, Any] | None = None,
        *,
        headers: dict[str, str] | None = None,
    ) -> Any:
        """
        Execute a registered IT tool.

        Args:
            tool_name:
                Name of the tool requested by the LLM.

            arguments:
                JSON-compatible arguments generated by the LLM.

            headers:
                Request headers that should be forwarded to the
                downstream IT Service.

        Returns:
            Result returned by the registered tool.

        Raises:
            ITToolExecutionError:
                If the tool does not exist, arguments are invalid,
                or execution fails.
        """

        arguments = arguments or {}

        logger.info(
            "Preparing IT tool execution",
            tool_name=tool_name,
        )

        if not tool_registry.exists(tool_name):
            logger.warning(
                "LLM requested unknown IT tool",
                tool_name=tool_name,
            )
            raise ITToolExecutionError(
                f"Unknown IT tool: {tool_name}"
            )

        handler = tool_registry.get(tool_name)

        try:
            validated_arguments = self._validate_arguments(
                handler=handler,
                arguments=arguments,
            )

            # Headers come from the authenticated incoming request,
            # not from LLM-generated arguments.
            signature = inspect.signature(handler)

            if "headers" in signature.parameters:
                validated_arguments["headers"] = headers

            logger.info(
                "Executing IT tool",
                tool_name=tool_name,
            )

            result = handler(**validated_arguments)

            if inspect.isawaitable(result):
                result = await result

            logger.info(
                "IT tool execution completed",
                tool_name=tool_name,
            )

            return result

        except ITToolExecutionError:
            raise

        except ValidationError as exc:
            logger.warning(
                "Invalid IT tool arguments",
                tool_name=tool_name,
                error=str(exc),
            )

            raise ITToolExecutionError(
                f"Invalid arguments for IT tool '{tool_name}'."
            ) from exc

        except TypeError as exc:
            logger.warning(
                "Unable to call IT tool",
                tool_name=tool_name,
                error=str(exc),
            )

            raise ITToolExecutionError(
                f"Invalid arguments for IT tool '{tool_name}'."
            ) from exc

        except Exception as exc:
            logger.exception(
                "IT tool execution failed",
                tool_name=tool_name,
                error=str(exc),
            )

            raise ITToolExecutionError(
                f"IT tool '{tool_name}' failed."
            ) from exc

    @staticmethod
    def _validate_arguments(
        *,
        handler: Any,
        arguments: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Validate LLM arguments using the handler's Python annotations.

        Pydantic TypeAdapter handles conversions such as:

            "550e8400-e29b-41d4-a716-446655440000"
                -> UUID(...)

        and:

            {
                "assigned_to": "..."
            }
                -> AssignDeviceRequest(...)
        """

        signature = inspect.signature(handler)

        try:
            type_hints = get_type_hints(handler)
        except (NameError, TypeError):
            type_hints = {}

        allowed_arguments = {
            name
            for name in signature.parameters
            if name != "headers"
        }

        unknown_arguments = set(arguments) - allowed_arguments

        if unknown_arguments:
            unknown = ", ".join(sorted(unknown_arguments))

            raise ITToolExecutionError(
                f"Unexpected arguments for IT tool: {unknown}"
            )

        validated: dict[str, Any] = {}

        for name, parameter in signature.parameters.items():
            if name == "headers":
                continue

            if name not in arguments:
                if parameter.default is inspect.Parameter.empty:
                    raise ITToolExecutionError(
                        f"Missing required argument: {name}"
                    )

                continue

            value = arguments[name]

            annotation = type_hints.get(
                name,
                parameter.annotation,
            )

            if annotation is inspect.Parameter.empty:
                validated[name] = value
                continue

            validated[name] = TypeAdapter(annotation).validate_python(
                value
            )

        return validated


it_tool_executor = ITToolExecutor()