"""Remove approval fields

Revision ID: 097f17259a78
Revises: 7a2a73560b31
Create Date: 2026-07-16 14:35:58.872412

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '097f17259a78'
down_revision: Union[str, Sequence[str], None] = '7a2a73560b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###