"""Initial IT Service

Revision ID: 7a2a73560b31
Revises: 
Create Date: 2026-07-16 11:39:58.572135

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '7a2a73560b31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.Enum('VPN', 'APPLICATION', 'DATABASE', name='accessrequesttype'), nullable=False),
    sa.Column('target_resource', sa.String(length=255), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REVOKED', name='accessrequeststatus'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_access_requests_requested_by', 'access_requests', ['requested_by'], unique=False)
    op.create_index('ix_access_requests_status', 'access_requests', ['status'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('LAPTOP', 'DESKTOP', 'MONITOR', 'PHONE', 'OTHER', name='assetcategory'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'UNDER_MAINTENANCE', 'DISPOSED', name='assetstatus'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index('ix_assets_assigned_to', 'assets', ['assigned_to'], unique=False)
    op.create_index('ix_assets_serial_number', 'assets', ['serial_number'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'REPAIR', 'RETIRED', name='devicestatus'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_devices_assigned_to', 'devices', ['assigned_to'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('maintenance_type', sa.Enum('PREVENTIVE', 'CORRECTIVE', name='maintenancetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('vendor_contact', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='maintenancestatus'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maintenance_records_device_id', 'maintenance_records', ['device_id'], unique=False)
    op.create_index('ix_maintenance_records_status', 'maintenance_records', ['status'], unique=False)
    op.create_table('software',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('publisher', sa.String(length=150), nullable=False),
    sa.Column('license_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('HARDWARE', 'SOFTWARE', 'NETWORK', 'VPN', 'ACCESS_CONTROL', 'EMAIL', 'SECURITY', 'LICENSE', 'PRINTER', 'OTHER', name='ticketcategory'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'CANCELLED', name='ticketstatus'), nullable=False),
    sa.Column('source', sa.Enum('WEB', 'MOBILE', 'EMAIL', 'AI_AGENT', 'ADMIN', name='ticketsource'), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.Enum('FIXED', 'WORKAROUND', 'DUPLICATE', 'CANNOT_REPRODUCE', 'NOT_AN_ISSUE', name='ticketresolution'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_index('ix_ticket_assigned_to', 'tickets', ['assigned_to'], unique=False)
    op.create_index('ix_ticket_priority', 'tickets', ['priority'], unique=False)
    op.create_index('ix_ticket_requester', 'tickets', ['requester_id'], unique=False)
    op.create_index('ix_ticket_status', 'tickets', ['status'], unique=False)
    op.create_index('ix_ticket_ticket_number', 'tickets', ['ticket_number'], unique=False)
    op.create_table('device_maintenance_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('performed_by', sa.String(length=150), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_maintenance_device_id', 'device_maintenance_history', ['device_id'], unique=False)
    op.create_table('installed_software',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('software_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_installed_software_device_id', 'installed_software', ['device_id'], unique=False)
    op.create_index('ix_installed_software_software_id', 'installed_software', ['software_id'], unique=False)
    op.create_index('ix_installed_software_user_id', 'installed_software', ['user_id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('software_id', sa.UUID(), nullable=True),
    sa.Column('license_key', sa.String(length=255), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('used_seats', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('renewal_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('software_installation_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('software_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='installationrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_install_req_software_id', 'software_installation_requests', ['software_id'], unique=False)
    op.create_index('ix_install_req_user_id', 'software_installation_requests', ['user_id'], unique=False)
    op.create_table('ticket_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_activity_performed_by', 'ticket_activity_logs', ['performed_by'], unique=False)
    op.create_index('ix_ticket_activity_ticket_id', 'ticket_activity_logs', ['ticket_id'], unique=False)
    op.create_table('ticket_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_attachments_ticket_id', 'ticket_attachments', ['ticket_id'], unique=False)
    op.create_index('ix_ticket_attachments_uploaded_by', 'ticket_attachments', ['uploaded_by'], unique=False)
    op.create_table('ticket_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.Enum('PUBLIC', 'INTERNAL', name='commenttype'), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_comments_author_id', 'ticket_comments', ['author_id'], unique=False)
    op.create_index('ix_ticket_comments_ticket_id', 'ticket_comments', ['ticket_id'], unique=False)
    op.create_table('license_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('license_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_license_assignments_assigned_to', 'license_assignments', ['assigned_to'], unique=False)
    op.create_index('ix_license_assignments_license_id', 'license_assignments', ['license_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_license_assignments_license_id', table_name='license_assignments')
    op.drop_index('ix_license_assignments_assigned_to', table_name='license_assignments')
    op.drop_table('license_assignments')
    op.drop_index('ix_ticket_comments_ticket_id', table_name='ticket_comments')
    op.drop_index('ix_ticket_comments_author_id', table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index('ix_ticket_attachments_uploaded_by', table_name='ticket_attachments')
    op.drop_index('ix_ticket_attachments_ticket_id', table_name='ticket_attachments')
    op.drop_table('ticket_attachments')
    op.drop_index('ix_ticket_activity_ticket_id', table_name='ticket_activity_logs')
    op.drop_index('ix_ticket_activity_performed_by', table_name='ticket_activity_logs')
    op.drop_table('ticket_activity_logs')
    op.drop_index('ix_install_req_user_id', table_name='software_installation_requests')
    op.drop_index('ix_install_req_software_id', table_name='software_installation_requests')
    op.drop_table('software_installation_requests')
    op.drop_table('licenses')
    op.drop_index('ix_installed_software_user_id', table_name='installed_software')
    op.drop_index('ix_installed_software_software_id', table_name='installed_software')
    op.drop_index('ix_installed_software_device_id', table_name='installed_software')
    op.drop_table('installed_software')
    op.drop_index('ix_device_maintenance_device_id', table_name='device_maintenance_history')
    op.drop_table('device_maintenance_history')
    op.drop_index('ix_ticket_ticket_number', table_name='tickets')
    op.drop_index('ix_ticket_status', table_name='tickets')
    op.drop_index('ix_ticket_requester', table_name='tickets')
    op.drop_index('ix_ticket_priority', table_name='tickets')
    op.drop_index('ix_ticket_assigned_to', table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('software')
    op.drop_index('ix_maintenance_records_status', table_name='maintenance_records')
    op.drop_index('ix_maintenance_records_device_id', table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index('ix_devices_assigned_to', table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_assets_serial_number', table_name='assets')
    op.drop_index('ix_assets_assigned_to', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_access_requests_status', table_name='access_requests')
    op.drop_index('ix_access_requests_requested_by', table_name='access_requests')
    op.drop_table('access_requests')
    # ### end Alembic commands ###