"""add_all_policies_tables

Revision ID: 21a410172480
Revises: f949296f2426
Create Date: 2026-07-20 22:01:17.580424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a410172480'
down_revision: Union[str, Sequence[str], None] = 'f949296f2426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_policies',
    sa.Column('working_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('grace_period', sa.Integer(), nullable=False),
    sa.Column('late_mark_limit', sa.Integer(), nullable=False),
    sa.Column('half_day_after_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('auto_checkout', sa.Boolean(), nullable=False),
    sa.Column('weekend_policy', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holiday_policies',
    sa.Column('calendar_name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('floating_holidays', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_policies',
    sa.Column('casual_leave_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('sick_leave_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('earned_leave_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('maternity_leave_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('paternity_leave_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('carry_forward_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_carry_forward', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('half_day_allowed', sa.Boolean(), nullable=False),
    sa.Column('minimum_notice_days', sa.Integer(), nullable=False),
    sa.Column('requires_attachment', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('probation_policies',
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('review_after_months', sa.Integer(), nullable=False),
    sa.Column('confirmation_required', sa.Boolean(), nullable=False),
    sa.Column('notice_period', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_policies',
    sa.Column('shift_start', sa.Time(), nullable=False),
    sa.Column('shift_end', sa.Time(), nullable=False),
    sa.Column('break_duration', sa.Integer(), nullable=False),
    sa.Column('weekly_off', sa.String(length=50), nullable=True),
    sa.Column('night_shift', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_policies')
    op.drop_table('probation_policies')
    op.drop_table('leave_policies')
    op.drop_table('holiday_policies')
    op.drop_table('attendance_policies')
    # ### end Alembic commands ###
