"""Create employee tables

Revision ID: adaa3fb0f7c9
Revises: b68feb94d859
Create Date: 2026-07-17 00:40:22.133856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adaa3fb0f7c9'
down_revision: Union[str, Sequence[str], None] = 'b68feb94d859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'employment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('employees', 'employment_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('employees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('employees_employee_code_key'), 'employees', type_='unique')
    op.drop_index(op.f('ix_employees_auth_user_id'), table_name='employees')
    op.create_index('uq_employees_auth_user_id_active', 'employees', ['auth_user_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index('uq_employees_employee_code_active', 'employees', ['employee_code'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_employees_employee_code_active', table_name='employees', postgresql_where=sa.text('is_active = true'))
    op.drop_index('uq_employees_auth_user_id_active', table_name='employees', postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_employees_auth_user_id'), 'employees', ['auth_user_id'], unique=True)
    op.create_unique_constraint(op.f('employees_employee_code_key'), 'employees', ['employee_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('employees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('employees', 'employment_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('employees', 'employment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
