"""Create organization table

Revision ID: fe6cb22b98c7
Revises: adaa3fb0f7c9
Create Date: 2026-07-17 10:02:57.285757

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'fe6cb22b98c7'
down_revision: str | Sequence[str] | None = 'adaa3fb0f7c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
