"""
Tool execution layer for the WorkPilot Workflow Agent.

Handles the dynamic execution of registered Workflow tools using arguments
provided by the LLM. It intercepts exceptions and standardizes results.
"""

from __future__ import annotations

import inspect
from typing import Any

from core.logger import get_logger
from modules.workflow.registry import workflow_tool_registry

logger = get_logger(__name__)


class WorkflowToolExecutionError(Exception):
    """Raised when a Workflow tool fails during execution."""
    pass


class WorkflowToolExecutor:
    """
    Executes Workflow tools safely using parameters requested by the LLM.
    """

    def __init__(self) -> None:
        self._registry = workflow_tool_registry

    async def execute(
        self,
        *,
        tool_name: str,
        arguments: dict[str, Any],
        headers: dict[str, str] | None = None,
    ) -> Any:
        """
        Execute a registered Workflow tool.

        Args:
            tool_name: The name of the tool to execute.
            arguments: The arguments generated by the LLM.
            headers: Optional HTTP headers (used for WorkPilot auth/context).

        Returns:
            The Python object returned by the tool (usually a dict or Pydantic model).

        Raises:
            WorkflowToolExecutionError: If the tool fails or cannot be found.
        """

        if not self._registry.exists(tool_name):
            logger.error(
                "LLM requested execution of an unknown Workflow tool",
                tool_name=tool_name,
            )
            raise WorkflowToolExecutionError(
                f"Unknown Workflow tool: '{tool_name}'"
            )

        handler = self._registry.get(tool_name)

        signature = inspect.signature(handler)
        if "headers" in signature.parameters:
            arguments["headers"] = headers or {}

        logger.info(
            "Executing Workflow tool",
            tool_name=tool_name,
            arguments_keys=list(arguments.keys()),
        )

        try:
            if inspect.iscoroutinefunction(handler):
                result = await handler(**arguments)
            else:
                result = handler(**arguments)

            logger.info(
                "Workflow tool executed successfully",
                tool_name=tool_name,
            )

            return result

        except Exception as exc:
            logger.exception(
                "Workflow tool execution failed",
                tool_name=tool_name,
                error=str(exc),
            )
            raise WorkflowToolExecutionError(
                f"Workflow tool '{tool_name}' failed: {exc}"
            ) from exc


workflow_tool_executor = WorkflowToolExecutor()
